"""Phase 10 — generic entity version history.

Every time a tracked entity (invoice, settings, workflow_run, ...)
changes, we copy a JSON snapshot of its *current* state into this
table *before* the mutation is committed. The ``version_number``
counts up per ``(entity_type, entity_id)`` so the same invoice
can be "v1 → v2 → v3" over its lifetime.

Restoring a previous version is a non-destructive operation: it
creates a *new* version row whose ``snapshot_json`` is the
restored content. The history is therefore append-only — the
spec's "restoring does not delete history" rule.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, Index, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from ..db import Base


class EntityVersion(Base):
    __tablename__ = "entity_versions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    # What this snapshot is for. Examples: "invoice", "workflow_run",
    # "settings", "extraction".
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    # The PK of the source row. Stored as a string so non-integer
    # entity IDs (e.g. "folder_rules") work too.
    entity_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    # 1-based version counter scoped to (entity_type, entity_id).
    version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    # Full JSON snapshot of the entity at this point in time.
    snapshot_json: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)
    # Free-text summary of what changed. e.g. "Edited vendor_name
    # and total_amount". Generated by the caller.
    change_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # Who/what produced this change. Examples: "user", "ai",
    # "workflow", "email_import", "parser", "voice".
    source_action: Mapped[str] = mapped_column(String(64), default="user", nullable=False)
    # "user" identifier or system actor.
    created_by: Mapped[str] = mapped_column(String(128), default="system", nullable=False)
    # Optional pointer to a parent version (the row we restored from
    # when this row was created by a restore). NULL for organic edits.
    restored_from_version: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False, index=True
    )

    __table_args__ = (
        Index(
            "ix_entity_versions_lookup",
            "entity_type",
            "entity_id",
            "version_number",
        ),
    )
