"""End-to-end API tests using FastAPI TestClient."""

from __future__ import annotations

import io

from fastapi.testclient import TestClient


def _make_pdf_bytes() -> bytes:
    """Build a real text PDF using PyMuPDF (already a dependency).

    Single page with the fields the parser expects.
    """
    import fitz
    doc = fitz.open()
    page = doc.new_page(width=612, height=792)
    text = (
        "ACME Office Supplies\n"
        "123 Industrial Way\n"
        "Springfield, IL 62704\n"
        "\n"
        "INVOICE\n"
        "\n"
        "Invoice Number: INV-2026-0042\n"
        "Invoice Date: 2026-05-12\n"
        "Due Date: 2026-06-11\n"
        "\n"
        "Description                  Qty   Unit Price   Line Total\n"
        "Printer Paper A4            10    4.50         45.00\n"
        "Toner Cartridge HP 26X      4     89.00        356.00\n"
        "Stapler Heavy Duty          2     14.75        29.50\n"
        "\n"
        "Subtotal: 430.50\n"
        "Tax (7%): 30.14\n"
        "Total: $460.64\n"
    )
    page.insert_text((50, 60), text, fontsize=11)
    data = doc.tobytes()
    doc.close()
    return data


def _make_jpeg_bytes() -> bytes:
    """1x1 white JPEG, valid header."""
    # Smallest valid JPEG, generated by Pillow would be ideal, but a fixed
    # 1x1 white JPEG works for "is it a JPEG" tests; OCR will be skipped in tests.
    return (
        b"\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00"
        b"\xff\xdb\x00C\x00\x08\x06\x06\x07\x06\x05\x08\x07\x07\x07\t\t"
        b"\x08\n\x0c\x14\r\x0c\x0b\x0b\x0c\x19\x12\x13\x0f\x14\x1d\x1a"
        b"\x1f\x1e\x1d\x1a\x1c\x1c $.' \",#\x0c\x1c(7),01444\x1f'9=82<.342"
        b"\xff\xc0\x00\x0b\x08\x00\x01\x00\x01\x01\x01\x11\x00"
        b"\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00"
        b"\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b"
        b"\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04"
        b"\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa"
        b"\x07\"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n"
        b"\x16\x17\x18\x19\x1a%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz"
        b"\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97\x98\x99"
        b"\x9a\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xb2\xb3\xb4\xb5\xb6\xb7"
        b"\xb8\xb9\xba\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xd2\xd3\xd4\xd5"
        b"\xd6\xd7\xd8\xd9\xda\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xf1"
        b"\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa"
        b"\xff\xda\x00\x08\x01\x01\x00\x00?\x00T\xdb\x9e\xa3\x89\x12\xd1\xff\xd9"
    )


def test_health(client: TestClient):
    r = client.get("/api/health")
    assert r.status_code == 200
    body = r.json()
    assert body["ok"] is True
    # Phases 1-12 all serve /api/health; the active phase is reported.
    assert body["phase"] in (1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23)


def test_cors_allows_tauri_webview_origin(client: TestClient):
    """Phase 9 — the Tauri 2 webview loads the bundled UI from
    ``http://tauri.localhost`` on Windows. The CORS allowlist
    must include that origin (and the legacy ``tauri://localhost``)
    so the React sidecar status poll does not get a TypeError:
    "Failed to fetch" from the webview's CORS layer."""
    for origin in (
        "http://tauri.localhost",
        "https://tauri.localhost",
        "tauri://localhost",
        "http://localhost:5173",
    ):
        r = client.get(
            "/api/health",
            headers={"Origin": origin},
        )
        assert r.status_code == 200
        # CORSMiddleware echoes the origin back when it's in
        # the allowlist; a missing header means the request was
        # blocked.
        assert r.headers.get("access-control-allow-origin") == origin, (
            f"origin {origin!r} not in CORS allowlist"
        )


def test_upload_rejects_unsupported_type(client: TestClient):
    r = client.post(
        "/api/invoices/upload",
        files={"file": ("note.txt", io.BytesIO(b"hello"), "text/plain")},
    )
    assert r.status_code == 415
    assert "Unsupported" in r.json()["detail"]


def test_upload_rejects_empty(client: TestClient):
    r = client.post(
        "/api/invoices/upload",
        files={"file": ("empty.pdf", io.BytesIO(b""), "application/pdf")},
    )
    assert r.status_code == 400


def test_upload_text_pdf_extracts_fields(client: TestClient):
    pdf = _make_pdf_bytes()
    r = client.post(
        "/api/invoices/upload",
        files={"file": ("sample.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    assert r.status_code == 201, r.text
    data = r.json()
    assert data["invoice_number"] == "INV-2026-0042"
    assert data["total_amount"] == 460.64
    assert data["currency"] == "USD"
    assert data["confidence_score"] > 0
    # Phase 3 renamed PENDING → READY_FOR_APPROVAL. Either of these is
    # acceptable depending on whether the parser cleanly extracted the
    # synthetic PDF.
    assert data["status"] in ("ready_for_approval", "needs_review")


def test_upload_image_creates_invoice_with_extraction_warnings(client: TestClient):
    jpg = _make_jpeg_bytes()
    r = client.post(
        "/api/invoices/upload",
        files={"file": ("scan.jpg", io.BytesIO(jpg), "image/jpeg")},
    )
    assert r.status_code == 201, r.text
    data = r.json()
    assert data["status"] in ("ready_for_approval", "needs_review")
    # OCR is disabled in tests, so we expect a needs_review status.
    assert data["status"] == "needs_review"
    assert any("OCR" in w or "Image" in w for w in data["warnings_json"])


def test_edit_invoice_and_audit_log(client: TestClient):
    pdf = _make_pdf_bytes()
    r = client.post(
        "/api/invoices/upload",
        files={"file": ("a.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    inv_id = r.json()["id"]

    r2 = client.patch(f"/api/invoices/{inv_id}", json={"vendor_name": "Edited Co."})
    assert r2.status_code == 200, r2.text
    assert r2.json()["vendor_name"] == "Edited Co."

    logs = client.get("/api/audit-logs", params={"entity_id": inv_id}).json()
    actions = {l["action"] for l in logs}
    assert "upload" in actions
    assert "extraction" in actions
    assert "edit" in actions


def test_approve_then_export_excel(client: TestClient):
    pdf = _make_pdf_bytes()
    r = client.post(
        "/api/invoices/upload",
        files={"file": ("a.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    inv_id = r.json()["id"]

    # Edit fields to make sure required ones are present (PDFs are synthetic, so we
    # make the data deterministic before approving).
    client.patch(
        f"/api/invoices/{inv_id}",
        json={
            "vendor_name": "ACME Office Supplies",
            "invoice_number": "INV-2026-0042",
            "invoice_date": "2026-05-12",
            "due_date": "2026-06-11",
            "currency": "USD",
            "subtotal": 430.50,
            "tax": 30.14,
            "total_amount": 460.64,
        },
    )
    r2 = client.post(f"/api/invoices/{inv_id}/approve")
    assert r2.status_code == 200, r2.text
    assert r2.json()["status"] == "approved"

    r3 = client.get("/api/invoices/export/excel")
    assert r3.status_code == 200
    assert r3.headers["content-type"].startswith(
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
    # The body should be a real .xlsx (PK\x03\x04 ZIP header).
    assert r3.content[:4] == b"PK\x03\x04"


def test_reject_blocks_export(client: TestClient):
    pdf = _make_pdf_bytes()
    r = client.post(
        "/api/invoices/upload",
        files={"file": ("a.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    inv_id = r.json()["id"]
    client.patch(
        f"/api/invoices/{inv_id}",
        json={"vendor_name": "ACME", "invoice_number": "X1", "invoice_date": "2026-01-01",
              "currency": "USD", "total_amount": 1.0},
    )
    r2 = client.post(f"/api/invoices/{inv_id}/reject", params={"reason": "test"})
    assert r2.status_code == 200
    assert r2.json()["status"] == "rejected"

    # Exporting an Excel file should succeed but contain no rows for this invoice.
    r3 = client.get("/api/invoices/export/excel")
    assert r3.status_code == 200


def test_duplicate_upload_marked(client: TestClient):
    pdf = _make_pdf_bytes()
    r1 = client.post(
        "/api/invoices/upload",
        files={"file": ("a.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    assert r1.status_code == 201
    r2 = client.post(
        "/api/invoices/upload",
        files={"file": ("a-copy.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    assert r2.status_code == 201
    assert r2.json()["status"] == "duplicate"


def test_cannot_approve_duplicate(client: TestClient):
    pdf = _make_pdf_bytes()
    client.post(
        "/api/invoices/upload",
        files={"file": ("a.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    r2 = client.post(
        "/api/invoices/upload",
        files={"file": ("a-copy.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    dup_id = r2.json()["id"]
    r3 = client.post(f"/api/invoices/{dup_id}/approve")
    assert r3.status_code == 409


def test_list_and_get_invoice(client: TestClient):
    pdf = _make_pdf_bytes()
    r = client.post(
        "/api/invoices/upload",
        files={"file": ("a.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    inv_id = r.json()["id"]
    rlist = client.get("/api/invoices")
    assert rlist.status_code == 200
    assert any(i["id"] == inv_id for i in rlist.json())
    rget = client.get(f"/api/invoices/{inv_id}")
    assert rget.status_code == 200
    assert rget.json()["id"] == inv_id


def test_status_filter(client: TestClient):
    pdf = _make_pdf_bytes()
    r = client.post(
        "/api/invoices/upload",
        files={"file": ("a.pdf", io.BytesIO(pdf), "application/pdf")},
    )
    inv_id = r.json()["id"]
    r2 = client.get("/api/invoices", params={"status": "ready_for_approval"})
    assert r2.status_code == 200
    assert any(i["id"] == inv_id for i in r2.json())
