from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ToolDef:
    name: str
    description: str
    risk_level: str
    approval_required: bool
    can_run_in_dry_run: bool
    audit_required: bool
    snapshot_required: bool
    input_schema: dict = field(default_factory=lambda: {"type": "object", "properties": {}})
    output_schema: dict = field(default_factory=lambda: {"type": "object", "properties": {}})


TOOL_REGISTRY: list[ToolDef] = [
    # ═══════════════════════════════════════════════════════════════════════
    # Browser Automation Tools
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="browser_open_url",
        description="Open a browser to a specified URL (domain-allowlisted only)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="browser_wait_for_user_login",
        description="Wait for the user to manually log in to a website (no passwords stored or automated)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="browser_click",
        description="Click a safe element on a web page (pre-approved selector only)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="browser_type",
        description="Type pre-approved text into a browser input field",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="browser_hotkey",
        description="Send a keyboard shortcut to the active browser tab",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="browser_read_page",
        description="Read the visible text content from the current browser page",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="browser_wait_for_download",
        description="Wait for a browser download to complete and return the file path",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="browser_export_report",
        description="Export a report or page from a web app by clicking the export/save button",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="browser_close",
        description="Close the current browser tab or the entire browser session",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Desktop / Windows Automation Tools
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="desktop_get_active_window",
        description="Detect the active window title and application name",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="desktop_click",
        description="Click a pre-approved UI element on the Windows desktop",
        risk_level="high",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="desktop_type",
        description="Type pre-approved text into a Windows desktop application field",
        risk_level="high",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="desktop_hotkey",
        description="Send a global keyboard shortcut (e.g., Ctrl+C, Win+R)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="desktop_copy",
        description="Copy selected text or content from the active window to clipboard",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="desktop_paste",
        description="Paste clipboard content into the active window field",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="desktop_wait",
        description="Wait for a specified duration or until a window appears",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="desktop_open_app",
        description="Open a Windows application by name or path",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Screen / OCR Tools
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="screen_capture",
        description="Capture a screenshot of the current screen or active window",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="screen_read_text",
        description="Read text from the current screen using OCR",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="screen_find_button",
        description="Find a UI button or control on screen by label or type",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="screen_find_table",
        description="Detect a table or structured data region on screen",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="screen_confirm_state",
        description="Confirm that the current screen matches an expected state (text, button, window title)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Excel / Spreadsheet Automation Tools
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="excel_open_workbook",
        description="Open and inspect an Excel workbook to get sheet names and structure",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_create_workbook",
        description="Create a new Excel workbook file with headers",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_read_sheet",
        description="Read data from a specified sheet in an Excel workbook",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_write_cell",
        description="Write a value to a single cell in an Excel sheet",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_write_range",
        description="Write a range of values to an Excel sheet starting at a given cell",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_append_rows",
        description="Append rows to a sheet in an existing Excel workbook",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_save_workbook",
        description="Save the current workbook (optionally to a new path)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_apply_formula",
        description="Apply a formula to a cell in an Excel sheet (safety-validated)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_apply_total_formula",
        description="Apply a SUM formula to total a column in an Excel sheet",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_apply_sumif_formula",
        description="Apply a SUMIF formula in an Excel sheet",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_apply_lookup_formula",
        description="Apply a lookup formula (VLOOKUP / INDEX-MATCH / XLOOKUP) in an Excel sheet",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_verify_formula",
        description="Verify that a formula in a cell is safe and valid",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_format_header",
        description="Format the header row of an Excel sheet with bold text and blue fill",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_auto_size_columns",
        description="Auto-size column widths in an Excel sheet to fit content",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_freeze_top_row",
        description="Freeze the top row in an Excel sheet",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_apply_currency_format",
        description="Apply currency number format to a column in an Excel sheet",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_apply_date_format",
        description="Apply date format to a column in an Excel sheet",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_highlight_negative_values",
        description="Highlight negative values in red in an Excel column",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_add_total_row",
        description="Add a total row with SUM formula at the bottom of a sheet",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_detect_columns",
        description="Detect column names, types, and sample values from an Excel sheet",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_create_summary_sheet",
        description="Create a summary sheet with grouped totals from a data sheet",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_create_summary_from_file",
        description="Full pipeline: validate, auto-detect columns, create summary sheet, format, save copy",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_create_pivot_table",
        description="[COM] Create a pivot table using Excel COM automation (xlwings). Requires Excel installed.",
        risk_level="high",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_switch_workbooks",
        description="[COM] Copy a sheet from one workbook to another using Excel COM automation",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_advanced_formatting",
        description="[COM] Apply conditional formatting to a range using Excel COM automation",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_calculate_and_read",
        description="[COM] Force Excel to calculate formulas and read the computed value from a cell",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_create_chart",
        description="[COM] Create a chart in an Excel workbook using COM automation",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_compare_workbooks",
        description="Compare two Excel workbooks and report row-level differences",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_clean_csv",
        description="Clean a CSV file by removing empty rows/columns and convert to Excel",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="excel_split_by_category",
        description="Split data in an Excel sheet into separate sheets by category",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="excel_export_pdf",
        description="Export an Excel sheet as PDF (placeholder, requires external tool)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Google Sheets Placeholder Tools
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="google_sheets_create_sheet",
        description="[Not Configured] Create a new Google Sheet. Requires Google OAuth setup.",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="google_sheets_read_sheet",
        description="[Not Configured] Read data from a Google Sheet. Requires Google OAuth setup.",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="google_sheets_write_range",
        description="[Not Configured] Write data to a Google Sheet range. Requires Google OAuth setup.",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="google_sheets_apply_formula",
        description="[Not Configured] Apply a formula in a Google Sheet. Requires Google OAuth setup.",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="google_sheets_export_xlsx",
        description="[Not Configured] Export a Google Sheet as Excel. Requires Google OAuth setup.",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # File / Folder Automation Tools
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="file_open",
        description="Open a file from local storage in its default application",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="file_open_folder",
        description="Open a folder in file explorer",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="file_copy",
        description="Copy a file or folder to a destination (creates backup snapshot)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="file_move",
        description="Move a file or folder to a new location (creates backup snapshot)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="file_rename",
        description="Rename a file or folder (creates backup snapshot)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="file_create_folder",
        description="Create a new folder at the specified path",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="file_watch_folder",
        description="Watch a folder for new or changed files",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="file_find_latest_download",
        description="Find the most recent file in the downloads folder",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="file_find_in_downloads",
        description="Search Downloads folder for files matching a query by filename. Returns metadata (filename, path, size, modified_at). If one match returns selected_file; if multiple returns needs_file_selection with options; if none returns needs_file_picker.",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
        input_schema={"type": "object", "properties": {
            "query": {"type": "string", "description": "Filename search query (e.g. 'parcel layer')"},
            "extensions": {"type": "array", "items": {"type": "string"}, "description": "File extensions to filter (e.g. '.xlsx', '.csv')"},
            "max_results": {"type": "integer", "description": "Maximum number of results to return"},
        }},
    ),
    ToolDef(
        name="file_copy_table_to_excel",
        description="Copy a table from a file or screen into an Excel sheet",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Email Automation Tools (Phase 34 — Gmail Read-Only)
    # ═══════════════════════════════════════════════════════════════════════
    # IMPORTANT: Phase 34 is GMAIL READ-ONLY ONLY. The following tools are
    # the ONLY email tools that exist. No send, forward, delete, move,
    # mark-read, modify, archive, or label tools are registered. The Gmail
    # OAuth scope is hardcoded to 'gmail.readonly'. Any plan step that
    # attempts an email write action is blocked at the safety-gate level
    # (classify_task_risk) and at the executor level (execute_tool).
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="email_connect_gmail",
        description="Connect Gmail read-only to enable email search and attachment download",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="email_search",
        description="Search emails by query (e.g. 'has:attachment invoice')",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="email_preview_messages",
        description="Preview email messages and their attachment metadata",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="email_download_attachments",
        description="Download email attachments to local storage (requires approval)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="email_save_attachment",
        description="Save a downloaded attachment file to a specified folder",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="email_disconnect_account",
        description="Disconnect Gmail account and revoke access",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # Legacy email tools (kept for backward compatibility)
    ToolDef(
        name="email_open",
        description="[Legacy] Open email inbox — use email_search instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="email_create_draft",
        description="[Legacy] Create a draft email (does not send)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="email_open_message",
        description="[Legacy] Open a specific email message — use email_preview_messages instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Workflow / Skill Management Tools
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="workflow_record_start",
        description="Start recording user actions to build a new workflow skill",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="workflow_record_stop",
        description="Stop recording and convert recorded actions into a skill draft",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="workflow_save_as_skill",
        description="Save a recorded or planned workflow as a reusable Accounting Skill",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="workflow_dry_run",
        description="Execute a saved skill or workflow in dry-run mode (no real changes)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="workflow_replay",
        description="Replay a previously saved workflow or skill in live mode",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="workflow_restore_version",
        description="Restore a previous version of a workflow or skill",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Safety / Audit / Validation Tools
    # ── Accounting Write-Back Tools (Phase 43) ──────────────────────────────
    ToolDef(
        name="quickbooks_create_bill",
        description="Create a real Bill in QuickBooks. HIGH RISK — requires explicit user approval and live mode. Creates an Accounts Payable bill with vendor name, line items, total amount, and due date.",
        risk_level="high",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
        input_schema={
            "type": "object",
            "properties": {
                "vendor_name": {"type": "string", "description": "Vendor/supplier name for the bill"},
                "line_items": {"type": "array", "items": {"type": "object", "properties": {
                    "description": {"type": "string"},
                    "amount": {"type": "number"},
                    "account": {"type": "string", "description": "QuickBooks account name (e.g. Office Supplies)"},
                }}},
                "total_amount": {"type": "number", "description": "Total bill amount"},
                "due_date": {"type": "string", "description": "Due date in YYYY-MM-DD format"},
            },
            "required": ["vendor_name", "total_amount"],
        },
    ),
    ToolDef(
        name="xero_create_bill",
        description="Create a real Bill (ACCPAY Invoice) in Xero. HIGH RISK — requires explicit user approval and live mode. Creates an Accounts Payable invoice with contact name, line items, total amount, and due date.",
        risk_level="high",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
        input_schema={
            "type": "object",
            "properties": {
                "vendor_name": {"type": "string", "description": "Contact/supplier name for the bill"},
                "line_items": {"type": "array", "items": {"type": "object", "properties": {
                    "description": {"type": "string"},
                    "amount": {"type": "number"},
                    "account_code": {"type": "string", "description": "Xero account code (e.g. 400)"},
                }}},
                "total_amount": {"type": "number", "description": "Total bill amount"},
                "due_date": {"type": "string", "description": "Due date in YYYY-MM-DD format"},
            },
            "required": ["vendor_name", "total_amount"],
        },
    ),
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="approval_request",
        description="Request user approval before executing a critical step",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="approval_confirm",
        description="Confirm user approval for a pending step",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="emergency_stop",
        description="Immediately stop all running automation and prevent new actions",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="audit_log",
        description="Write an entry to the audit log for compliance",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=False,
        snapshot_required=False,
    ),
    ToolDef(
        name="snapshot_create",
        description="Create a file snapshot before making changes (backup)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="sensitive_redact",
        description="Redact sensitive values (passwords, tokens, PII) from output",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=False,
        snapshot_required=False,
    ),
    ToolDef(
        name="validate_result",
        description="Validate a result against expected criteria",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Legacy / Deprecated Tools
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="read_pdf",
        description="[Legacy] Read text content from a PDF file (use screen or browser tools instead)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=False,
        snapshot_required=False,
    ),
    ToolDef(
        name="extract_invoice_data",
        description="[Legacy] Extract structured data from a file (use email_download_attachments + file tools)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="scan_local_folder",
        description="[Legacy] Scan a local folder for invoice files. Use file_watch_folder or file_find_latest_download instead.",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="create_daily_invoices_excel",
        description="[Legacy] Create Daily Invoices Excel workbook (use excel_create_summary_sheet instead)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    # ── Legacy P&L Comparison Tools (kept for existing workflows) ────────
    ToolDef(
        name="open_accounting_platform",
        description="[Legacy] Open the accounting platform (use browser_open_url instead)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="wait_for_manual_login",
        description="[Legacy] Wait for manual login (use browser_wait_for_user_login instead)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="navigate_to_profit_loss_report",
        description="[Legacy] Navigate to P&L report in accounting platform (use browser tools instead)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="set_report_date_range",
        description="[Legacy] Set date range on accounting report (use browser tools instead)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="export_accounting_report",
        description="[Legacy] Export accounting report from platform (use browser_export_report instead)",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="watch_downloaded_report",
        description="[Legacy] Wait for exported report file — use browser_wait_for_download instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="read_pnl_report_file",
        description="[Legacy] Read P&L report from file — use file_open + screen tools instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="normalize_pnl_report",
        description="[Legacy] Normalize P&L report rows — handled automatically by new skills",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="compare_pnl_reports",
        description="[Legacy] Compare two P&L reports — use excel_compare_workbooks instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="create_pnl_comparison_excel",
        description="[Legacy] Create P&L comparison Excel — use excel_create_summary_sheet instead",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="speak_pnl_difference",
        description="[Legacy] Speak P&L comparison summary — use speak_response instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=False,
        snapshot_required=False,
    ),
    ToolDef(
        name="save_report_workflow",
        description="[Legacy] Save P&L comparison as workflow — use workflow_save_as_skill instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    # ── Legacy Core Tools (kept for backward compatibility) ──────────────
    ToolDef(
        name="open_email",
        description="[Legacy] Open email inbox — use email_open instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="search_email",
        description="[Legacy] Search emails — use email_search instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="download_attachments",
        description="[Legacy] Download attachments — use email_download_attachments instead",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="open_browser",
        description="[Legacy] Open browser URL — use browser_open_url instead",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="read_current_screen",
        description="[Legacy] Read screen text — use screen_read_text instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="click_approved_target",
        description="[Legacy] Click UI element — use desktop_click or browser_click instead",
        risk_level="high",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="type_approved_text",
        description="[Legacy] Type text — use desktop_type or browser_type instead",
        risk_level="high",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="copy_table_to_excel",
        description="[Legacy] Copy table to Excel — use file_copy_table_to_excel instead",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="open_file",
        description="[Legacy] Open file — use file_open instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="open_folder",
        description="[Legacy] Open folder — use file_open_folder instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="save_workflow",
        description="[Legacy] Save workflow — use workflow_save_as_skill instead",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="replay_workflow",
        description="[Legacy] Replay workflow — use workflow_replay instead",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="calculate_excel_total",
        description="[Legacy] Calculate column total by code (use excel_add_total_row or formula tool instead)",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="create_excel_workbook",
        description="[Legacy] Create Excel workbook — use excel_create_workbook instead",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="append_excel_rows",
        description="[Legacy] Append rows — use excel_append_rows instead",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    ToolDef(
        name="create_excel_summary",
        description="[Legacy] Create Excel summary — use excel_create_summary_sheet instead",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    # ── Phase 39: Cloud Storage Tools (Google Drive — Read-Only) ────────────
    ToolDef(
        name="drive_list_recent_files",
        description="List recent files from Google Drive, optionally filtered by keywords",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=False,
        snapshot_required=False,
        input_schema={
            "type": "object",
            "properties": {
                "days_back": {"type": "integer", "description": "Number of days to look back (default 7)"},
                "keywords": {"type": "array", "items": {"type": "string"}, "description": "Optional keywords to filter file names"},
            },
        },
    ),
    ToolDef(
        name="drive_download_file",
        description="Download a file from Google Drive to a local secure folder",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=False,
        snapshot_required=False,
        input_schema={
            "type": "object",
            "properties": {
                "file_id": {"type": "string", "description": "Google Drive file ID to download"},
                "target_folder": {"type": "string", "description": "Optional target folder path (defaults to data_dir/drive_downloads/{user_id}/)"},
            },
        },
    ),
    # ── Phase 41: Semantic Memory & RAG Tools ──────────────────────────────
    ToolDef(
        name="semantic_search_invoices",
        description="Search indexed invoice data using natural language queries. Returns the best-matching invoices with vendor, amount, date, and file path.",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
        input_schema={
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Natural language search query (e.g. 'invoices over $1000 from Acme Corp')"},
                "top_k": {"type": "integer", "description": "Number of results to return (default 5)"},
            },
            "required": ["query"],
        },
    ),
    # ── Phase 39: Background Daemon & Analytics Tools ──────────────────────
    ToolDef(
        name="analyze_invoice_dataset",
        description="Calculate aggregate statistics (sum, count, avg, min/max) from an invoice dataset",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=False,
        snapshot_required=False,
        input_schema={
            "type": "object",
            "properties": {
                "invoices_data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "vendor": {"type": "string"},
                            "total_amount": {"type": "number"},
                            "date": {"type": "string"},
                        },
                    },
                },
            },
        },
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 45A: Bank Reconciliation Tools
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="bank_parse_feed",
        description="Parse a bank feed CSV or JSON file into structured transactions",
        risk_level="low",
        approval_required=False,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=False,
    ),
    ToolDef(
        name="bank_reconcile_and_report",
        description="Match bank transactions to invoices using semantic search and generate a color-coded Excel report",
        risk_level="medium",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
    ),
    # ═══════════════════════════════════════════════════════════════════════
    # Phase 45B: Live Excel Editing (Active Workbook COM)
    # ═══════════════════════════════════════════════════════════════════════
    ToolDef(
        name="excel_live_edit_active_workbook",
        description="Connect to the active visible Excel workbook and execute live editing commands (format, write values, insert pivot, chart, etc.) via COM automation. HIGH RISK: edits the user's active workbook directly with an undo snapshot.",
        risk_level="high",
        approval_required=True,
        can_run_in_dry_run=True,
        audit_required=True,
        snapshot_required=True,
        input_schema={
            "type": "object",
            "properties": {
                "command_type": {
                    "type": "string",
                    "enum": [
                        "format_range", "set_value", "write_values", "apply_formula",
                        "clear_range", "conditional_format", "insert_pivot", "insert_chart",
                        "read_range", "get_active_cell", "list_sheets", "activate_sheet",
                    ],
                    "description": "The type of live edit command to execute on the active workbook",
                },
                "params": {
                    "type": "object",
                    "description": "Parameters for the command (range, value, formula, color, etc.)",
                },
            },
            "required": ["command_type", "params"],
        },
    ),
]


def get_tool(name: str) -> ToolDef | None:
    for t in TOOL_REGISTRY:
        if t.name == name:
            return t
    return None


def list_tools() -> list[ToolDef]:
    return list(TOOL_REGISTRY)


def list_tools_by_risk(risk_level: str) -> list[ToolDef]:
    return [t for t in TOOL_REGISTRY if t.risk_level == risk_level]


def list_tools_by_category(pattern: str = "") -> list[ToolDef]:
    if not pattern:
        return list(TOOL_REGISTRY)
    return [t for t in TOOL_REGISTRY if t.name.startswith(pattern)]


def validate_tool_plan(tool_name: str, params: dict) -> tuple[bool, str | None]:
    tool = get_tool(tool_name)
    if not tool:
        return False, f"Unknown tool: {tool_name}"
    return True, None
